# Generated by Django 5.2.8 on 2025-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
