# Generated by Django 5.2.8 on 2025-12-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_article_dislike_count_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
