# Generated by Django 5.2.8 on 2025-12-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
    ]
