# Generated by Django 5.2.8 on 2025-12-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
